### ISSUE TITLE
Json.NetMF 1.3.0.0 installed successfully, but complains of missing some assembly when loading

### ISSUE THREAD

**Issue by JB16** [nanoframework/Json.NetMF#10]
Json.NetMF was installed via PM (command-line) on NetMF 4.4. There are no dependencies listed for this version of NetMF, so assumed all was good until I tried loading onto target (the special chars in the error statement are as they appear and haven't been modified).

Does anyone have an idea of what might be the missing assembly here? (mscorlib 4.4.0.0 is present)

Assembly: Json.NetMF (1.3.0.0) Attaching deployed file.

Assembly: System.IO (4.4.0.0) Attaching deployed file.

Assembly: AP200NetMFApplication (1.0.0.0) Resolving.

Link failure: some assembly references cannot be resolved!!

Assembly: Json.NetMF (1.3.0.0) needs assembly '�~��(B����+��' (4.3.1.0)

Assembly: AP200NetMFApplication (1.0.0.0) needs assembly 'Json.NetMF' (1.3.0.0)

Error: a3000000

Waiting for debug commands...

The program '[5] Micro Framework application: Managed' has exited with code 0 (0x0).

**Comment by JB16** [comment]
Read somewhere that the error: a3000000 means there's a mismatch between the interpreter-code and application-code.

My question now is that apart from installing Json.NetMF, is there something else that might be required to be installed on the interpreter (netmf 4.4)?

**Comment by mweimer** [comment]
Most likely the library just needs to be recompiled against netmf 4.4 and the new assembly needs added to the nuget package. The last time this project was updated was when netmf 4.3 was released and it had to be recompiled against 4.3 because it previously was only working with 4.2.

The problem is I don't even run a windows pc anymore. If I have time soon, i may setup a windows vm, install VS, install netmf sdk and recompile this library for 4.4,  and update nuget.

**Comment by JB16** [comment]
Ah, good to know! If this branch is not undergoing constant monitoring/updating or even usage by others, would you mind suggesting an alternative  fr Json support for NetMF4.4, instead?

**Comment by JB16** [comment]
Hi Matt, I did, as you suggested - added 'existing project' to my project's solution explorer, rebuilt solution and added reference to the newly generated Json.NetMF.dll from my bin folder.

However, I still see the issue as stated above --
   Assembly: Json.NetMF (1.3.0.0)  Attaching deployed file.

   Assembly: System.IO (4.4.0.0)  Attaching deployed file.

   Assembly: AP200NetMFApplication (1.0.0.0)  Resolving.

Link failure: some assembly references cannot be resolved!!


Assembly: Json.NetMF (1.3.0.0) needs assembly '&' (4.3.1.0)

Assembly: AP200NetMFApplication (1.0.0.0) needs assembly 'Json.NetMF' (1.3.0.0)

Error: a3000000

Waiting for debug commands...

The program '[2] Micro Framework application: Managed' has exited with code 0 (0x0).

**Comment by josesimoes** [comment]
Hi @JB16 !
Json.NetMF is now under nanoFramework organization.
Despite the original Json.NetMF library is still being maintained we've added a new version for nanoFramework. nanoFramework has started as spin-off of .NETMF but, after almost 3 years of continued development, its way beyond .NETMF. You may want to check it out. 😉
