### ISSUE TITLE
camel casing props

### ISSUE THREAD

**Issue by rgavrilov** [nanoframework/Json.NetMF#7]
Is there a plan to add an option to camel-case serialized props?

**Comment by josesimoes** [comment]
Hi @rgavrilov!
Json.NetMF is now under nanoFramework organization.
Despite the original Json.NetMF library is still being maintained we've added a new version for nanoFramework. nanoFramework has started as spin-off of .NETMF but, after almost 3 years of continued development, its way beyond .NETMF. You may want to check it out. 😉
