### ISSUE TITLE
JsonSerializer ignore value for TimeSpan objects

### ISSUE THREAD

**Issue by gornialberto** [nanoframework/Json.NetMF#9]
Hi,

just adding such things should fix this:

 case "TimeSpan":
                    {
                        TimeSpan timeSpan = (TimeSpan)o;
                        return "\"" + timeSpan.Days + "d " + timeSpan.Hours + "h " + timeSpan.Minutes + "m "
                            + timeSpan.Seconds + "s " + timeSpan.Milliseconds + "m " + "\"";
                    }

**Comment by josesimoes** [comment]
Hi @gornialberto!
Json.NetMF is now under nanoFramework organization.
Despite the original Json.NetMF library is still being maintained we've added a new version for nanoFramework. nanoFramework has started as spin-off of .NETMF but, after almost 3 years of continued development, its way beyond .NETMF. You may want to check it out. 😉
